version: '3.8'

services:
  springerator-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springerator-app
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=springerator_redis_pass  # Obviously, in production we would set this securely. It is picked up by the application.yaml
    depends_on:
      - redis
    networks:
      - springerator-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: springerator-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - springerator-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass springerator_redis_pass # This configured the password here. Not using an ACL, but that's possible also, to limit the application to a key prefix.

networks:
  springerator-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
